services:
  - type: web
    name: spotify-web-quiz
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SPOTIFY_REDIRECT_URI
        value: https://spotifywebquiz.onrender.com/callback
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
